apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    meta.helm.sh/release-name: unguard
    meta.helm.sh/release-namespace: unguard
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: payment-service
    app.kubernetes.io/part-of: unguard
  name: unguard-payment-service
  namespace: unguard
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: payment-service
      app.kubernetes.io/part-of: unguard
  template:
    metadata:
      labels:
        app.kubernetes.io/name: payment-service
        app.kubernetes.io/part-of: unguard
    spec:
      serviceAccountName: unguard-user

      containers:
      - env:
        - name: SERVER_PORT
          value: "8084"
        - name: API_PATH
          value: /payment-service
        - name: OTEL_LOGS_EXPORTER
          value: none
        - name: OTEL_METRICS_EXPORTER
          value: none
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: service.name=unguard-payment-service
        - name: OTEL_TRACES_EXPORTER
          value: none
        - name: OTEL_EXPERIMENTAL_SDK_ENABLED
          value: "false"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: http://jaeger-collector:4318
        - name: OTEL_EXPORTER_OTLP_PROTOCOL
          value: http/protobuf
        - name: OTEL_PROPAGATORS
          value: jaeger
        - name: OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED
          value: "false"
        - name: PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION
          value: python
        image: ghcr.io/dynatrace-oss/unguard/unguard-payment-service:0.9.4
        imagePullPolicy: IfNotPresent
        name: payment-service
        securityContext:
          privileged: true
          runAsUser: 0
        ports:
        - containerPort: 8084
          protocol: TCP
        resources: {}
